########################
# access roleの一覧（database role）
########################
access_db_roles:
  - name: PRD_DB_READWRITE
    database: PRD_DB
    comment: 本番環境データベースでデータベースの削除以外何でも可能(ALL)
  - name: PRD_DB_READONLY
    database: PRD_DB
    comment: 本番環境データベースでデータベースの参照が可能(USAGE)
  - name: PRD_SCHEMA_A_READWRITE
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_A スキーマに対して読み書き可能
  - name: PRD_SCHEMA_A_READONLY
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_A スキーマに対して読み取り可能
  - name: PRD_SCHEMA_B_READWRITE
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_B スキーマに対して読み書き可能
  - name: PRD_SCHEMA_B_READONLY
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_B スキーマに対して読み取り可能
########################
# access roleの一覧（通常のロール）
########################
access_roles:
  - name: PRD_WAREHOUSE_USAGE
    comment: 本番環境用ウェアハウスを使用可能
  - name: PRD_WAREHOUSE_MODIFY
    comment: 本番環境用ウェアハウスの設定を修正可能
########################
# データベースのgrant
########################
grant_database_to_access_db_roles:
  - name: DATABASE_PRD_DB_READONLY
    type: DATABASE
    parameter:
      database_name: PRD_DB
      all_privileges: false
      privileges:
        - USAGE
        - MONITOR
    roles:
      - PRD_DB_READONLY
  - name: DATABASE_PRD_DB_READWRITE
    type: DATABASE
    parameter:
      database_name: PRD_DB
      all_privileges: true
      privileges:
        - ALL # resource定義上は不要だが、localでリスト化するループ処理の関係上記載
    roles:
      - PRD_DB_READWRITE
########################
# スキーマのgrant
########################
grant_schema_to_access_db_roles:
  - name: SCHEMA_PRD_DB_SCHEMA_A_READONLY
    type: SCHEMA
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_A
      all_privileges: false
      privileges:
        - USAGE
        - MONITOR
    roles:
      - PRD_SCHEMA_A_READONLY
  - name: SCHEMA_PRD_DB_SCHEMA_A_READWRITE
    type: SCHEMA
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_A
      all_privileges: true
      privileges:
        - ALL # resource定義上は不要だが、localでリスト化するループ処理の関係上記載
    roles:
      - PRD_SCHEMA_A_READWRITE
  - name: SCHEMA_PRD_DB_SCHEMA_B_READONLY
    type: SCHEMA
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_B
      all_privileges: false
      privileges:
        - USAGE
    roles:
      - PRD_SCHEMA_B_READONLY
  - name: SCHEMA_PRD_DB_SCHEMA_B_READWRITE
    type: SCHEMA
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_B
      all_privileges: true
      privileges:
        - ALL # resource定義上は不要だが、localでリスト化するループ処理の関係上記載
    roles:
      - PRD_SCHEMA_B_READWRITE
########################
# スキーマ内の全テーブルに関するgrant ※ここで定義したものがall in schemaとfuture in schemaとしてgrantされる
########################
grant_table_to_access_db_roles:
  - name: TABLE_PRD_DB_SCHEMA_A_READONLY
    type: TABLE
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_A
      all_privileges: false
      privileges:
        - SELECT
    roles:
      - PRD_SCHEMA_A_READONLY
  - name: TABLE_PRD_DB_SCHEMA_A_READWRITE
    type: TABLE
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_A
      all_privileges: true
      privileges:
        - ALL # resource定義上は不要だが、localでリスト化するループ処理の関係上記載
    roles:
      - PRD_SCHEMA_A_READWRITE
  - name: TABLE_PRD_DB_SCHEMA_B_READONLY
    type: TABLE
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_B
      all_privileges: false
      privileges:
        - SELECT
    roles:
      - PRD_SCHEMA_B_READONLY
  - name: TABLE_PRD_DB_SCHEMA_B_READWRITE
    type: TABLE
    parameter:
      database_name: PRD_DB
      schema_name: SCHEMA_B
      all_privileges: true
      privileges:
        - ALL # resource定義上は不要だが、localでリスト化するループ処理の関係上記載
    roles:
      - PRD_SCHEMA_B_READWRITE

########################
# ウェアハウスのgrant
########################
grant_warehouse_to_access_roles:
  - name: WAREHOUSE_TD_DEMO_USAGE
    type: WAREHOUSE
    parameter:
      warehouse_name: TF_DEMO
      privileges:
        - USAGE
        - MONITOR
    roles:
      - PRD_WAREHOUSE_USAGE
  - name: WAREHOUSE_TD_DEMO_MODIFY
    type: WAREHOUSE
    parameter:
      warehouse_name: TF_DEMO
      privileges:
        - USAGE
        - MONITOR
        - OPERATE
        - MODIFY
    roles:
      - PRD_WAREHOUSE_MODIFY