access_db_roles:
  - name: PRD_DB_READWRITE
    database: PRD_DB
    comment: 本番環境データベースでデータベースの削除以外何でも可能(ALL)
  - name: PRD_DB_READONLY
    database: PRD_DB
    comment: 本番環境データベースでデータベースの参照が可能(USAGE)
  - name: PRD_SCHEMA_A_READWRITE
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_A スキーマに対して読み書き可能
  - name: PRD_SCHEMA_A_READONLY
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_A スキーマに対して読み取り可能
  - name: PRD_SCHEMA_B_READWRITE
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_B スキーマに対して読み書き可能
  - name: PRD_SCHEMA_B_READONLY
    database: PRD_DB
    comment: 本番環境データベースで SCHEMA_B スキーマに対して読み取り可能
access_roles:
  - name: PRD_WAREHOUSE_USAGE
    comment: 本番環境用ウェアハウスを使用可能
  - name: PRD_WAREHOUSE_MODIFY
    comment: 本番環境用ウェアハウスの設定を修正可能
grant_on_object_to_access_db_roles:
  - name: DATABASE_PRD_DB_READONLY
    type: DATABASE
    parameter:
      database_name: PRD_DB
      all_privileges: false
      privileges:
        - USAGE
    roles:
      - PRD_DB_READONLY
  - name: DATABASE_PRD_DB_READWRITE
    type: DATABASE
    parameter:
      database_name: PRD_DB
      all_privileges: true
      privileges:
        - ALL # resource定義上は不要だが、localでリスト化するループ処理の関係上記載
    roles:
      - PRD_DB_READWRITE

grant_on_object_to_access_roles:
  - name: WAREHOUSE_TD_DEMO_USAGE
    type: WAREHOUSE
    parameter:
      warehouse_name: TF_DEMO
      privileges:
        - USAGE
        - MONITOR
    roles:
      - PRD_WAREHOUSE_USAGE
  - name: WAREHOUSE_TD_DEMO_MODIFY
    type: WAREHOUSE
    parameter:
      warehouse_name: TF_DEMO
      privileges:
        - USAGE
        - MONITOR
        - OPERATE
        - MODIFY
    roles:
      - PRD_WAREHOUSE_MODIFY